create extension if not exists pg_trgm with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  full_name text not null default '',
  username text,
  bio text not null default '',
  avatar_url text,
  role text not null default 'member'
    check (role in ('member', 'content_admin', 'support_admin', 'super_admin')),
  status text not null default 'active'
    check (status in ('active', 'paused', 'disabled')),
  last_active_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_email_not_blank check (btrim(email) <> ''),
  constraint profiles_username_not_blank check (
    username is null or btrim(username) <> ''
  )
);

create unique index profiles_email_lower_key on public.profiles (lower(email));
create unique index profiles_username_lower_key
  on public.profiles (lower(username))
  where username is not null;
create index profiles_role_idx on public.profiles (role);
create index profiles_status_idx on public.profiles (status);

create or replace function private.sync_auth_user_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested_role text := coalesce(new.raw_app_meta_data ->> 'role', 'member');
  requested_status text := coalesce(
    new.raw_app_meta_data ->> 'account_status',
    'active'
  );
begin
  if requested_role not in (
    'member',
    'content_admin',
    'support_admin',
    'super_admin'
  ) then
    requested_role := 'member';
  end if;

  if requested_status not in ('active', 'paused', 'disabled') then
    requested_status := 'active';
  end if;

  insert into public.profiles (
    id,
    email,
    full_name,
    username,
    avatar_url,
    role,
    status
  )
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    nullif(btrim(new.raw_user_meta_data ->> 'username'), ''),
    nullif(btrim(new.raw_user_meta_data ->> 'avatar_url'), ''),
    requested_role,
    requested_status
  )
  on conflict (id) do update
  set
    email = excluded.email,
    role = excluded.role,
    status = excluded.status,
    updated_at = now();

  return new;
end;
$$;

revoke execute on function private.sync_auth_user_profile() from public;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.sync_auth_user_profile();

create trigger on_auth_user_access_changed
after update of email, raw_app_meta_data on auth.users
for each row execute function private.sync_auth_user_profile();

create or replace function private.current_user_is_admin()
returns boolean
language sql
stable
set search_path = ''
as $$
  select coalesce(
    (select auth.jwt() -> 'app_metadata' ->> 'role') in (
      'content_admin',
      'support_admin',
      'super_admin'
    ),
    false
  );
$$;

create or replace function private.current_user_is_content_admin()
returns boolean
language sql
stable
set search_path = ''
as $$
  select coalesce(
    (select auth.jwt() -> 'app_metadata' ->> 'role') in (
      'content_admin',
      'super_admin'
    ),
    false
  );
$$;

grant usage on schema private to authenticated;
grant execute on function private.current_user_is_admin() to authenticated;
grant execute on function private.current_user_is_content_admin() to authenticated;

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  description text not null default '',
  is_active boolean not null default true,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_name_not_blank check (btrim(name) <> ''),
  constraint categories_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create unique index categories_name_lower_key on public.categories (lower(name));
create unique index categories_slug_lower_key on public.categories (lower(slug));
create index categories_created_by_idx on public.categories (created_by);
create index categories_active_name_idx on public.categories (name)
  where is_active;

create table public.statuses (
  id smallint generated by default as identity primary key,
  status text not null unique,
  label text not null,
  is_public boolean not null default false,
  sort_order smallint not null default 0,
  constraint statuses_status_format check (status ~ '^[a-z][a-z0-9_]*$'),
  constraint statuses_label_not_blank check (btrim(label) <> '')
);

create table public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid references public.profiles (id) on delete set null,
  category_id bigint not null references public.categories (id),
  status_id smallint not null references public.statuses (id),
  title text not null,
  slug text,
  description text not null,
  content text not null,
  image text not null default '',
  date date not null default current_date,
  published_at timestamptz,
  likes_count integer not null default 0 check (likes_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint posts_title_not_blank check (btrim(title) <> ''),
  constraint posts_description_not_blank check (btrim(description) <> ''),
  constraint posts_content_not_blank check (btrim(content) <> ''),
  constraint posts_slug_format check (
    slug is null or slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  )
);

create unique index posts_slug_lower_key
  on public.posts (lower(slug))
  where slug is not null;
create index posts_author_id_idx on public.posts (author_id);
create index posts_category_id_idx on public.posts (category_id);
create index posts_status_id_idx on public.posts (status_id);
create index posts_status_date_idx on public.posts (status_id, date desc, id desc);
create index posts_title_search_idx
  on public.posts using gin (title extensions.gin_trgm_ops);
create index posts_description_search_idx
  on public.posts using gin (description extensions.gin_trgm_ops);
create index posts_content_search_idx
  on public.posts using gin (content extensions.gin_trgm_ops);

create table public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts (id) on delete cascade,
  author_id uuid not null references public.profiles (id) on delete cascade,
  parent_id bigint,
  content text not null,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint comments_content_not_blank check (btrim(content) <> ''),
  constraint comments_id_post_id_key unique (id, post_id),
  constraint comments_parent_same_post_fkey
    foreign key (parent_id, post_id)
    references public.comments (id, post_id)
    on delete cascade
);

create index comments_post_created_idx
  on public.comments (post_id, created_at desc)
  where not is_deleted;
create index comments_author_id_idx on public.comments (author_id);
create index comments_parent_id_idx on public.comments (parent_id);

create table public.post_likes (
  post_id bigint not null references public.posts (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create index post_likes_user_id_idx on public.post_likes (user_id);

create or replace function private.refresh_post_likes_count()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  affected_post_id bigint := coalesce(new.post_id, old.post_id);
begin
  update public.posts
  set likes_count = (
    select count(*)::integer
    from public.post_likes
    where post_id = affected_post_id
  )
  where id = affected_post_id;

  return coalesce(new, old);
end;
$$;

revoke execute on function private.refresh_post_likes_count() from public;

create trigger refresh_post_likes_count
after insert or delete on public.post_likes
for each row execute function private.refresh_post_likes_count();

create table public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.profiles (id) on delete cascade,
  actor_id uuid references public.profiles (id) on delete set null,
  type text not null check (
    type in ('publish', 'comment', 'comment_reply', 'like', 'system')
  ),
  post_id bigint references public.posts (id) on delete cascade,
  comment_id bigint references public.comments (id) on delete cascade,
  title text not null default '',
  body text not null default '',
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index notifications_recipient_unread_idx
  on public.notifications (recipient_id, created_at desc)
  where read_at is null;
create index notifications_actor_id_idx on public.notifications (actor_id);
create index notifications_post_id_idx on public.notifications (post_id);
create index notifications_comment_id_idx on public.notifications (comment_id);

create table public.member_programs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  age smallint not null check (age between 13 and 120),
  weight_kg numeric(5,2) not null check (weight_kg between 20 and 500),
  height_cm numeric(5,2) not null check (height_cm between 100 and 250),
  gender text not null check (
    gender in ('male', 'female', 'prefer_not_to_say')
  ),
  goal text not null check (
    goal in ('muscle_gain', 'fat_loss', 'endurance', 'general_fitness')
  ),
  experience text not null check (
    experience in ('beginner', 'intermediate', 'advanced')
  ),
  days_per_week smallint not null check (days_per_week between 2 and 6),
  diet text not null check (
    diet in ('standard', 'high_protein', 'vegetarian', 'plant_based')
  ),
  restrictions text not null default '',
  workout_plan jsonb,
  nutrition_plan jsonb,
  status text not null default 'draft'
    check (status in ('draft', 'active', 'completed', 'archived')),
  is_active boolean not null default true,
  calculated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint member_programs_id_user_id_key unique (id, user_id),
  constraint member_programs_workout_plan_object check (
    workout_plan is null or jsonb_typeof(workout_plan) = 'object'
  ),
  constraint member_programs_nutrition_plan_object check (
    nutrition_plan is null or jsonb_typeof(nutrition_plan) = 'object'
  )
);

create unique index member_programs_one_active_per_user
  on public.member_programs (user_id)
  where is_active;
create index member_programs_user_created_idx
  on public.member_programs (user_id, created_at desc);

create table public.workout_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  program_id bigint,
  workout_date date not null default current_date,
  session_name text not null,
  duration_minutes smallint check (duration_minutes between 1 and 1440),
  completed boolean not null default false,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint workout_logs_session_name_not_blank check (btrim(session_name) <> ''),
  constraint workout_logs_program_owner_fkey
    foreign key (program_id, user_id)
    references public.member_programs (id, user_id)
    on delete set null (program_id)
);

create index workout_logs_user_date_idx
  on public.workout_logs (user_id, workout_date desc);
create index workout_logs_program_id_idx on public.workout_logs (program_id);

create table public.body_measurements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  measured_on date not null default current_date,
  weight_kg numeric(5,2) check (weight_kg between 20 and 500),
  body_fat_percent numeric(5,2) check (body_fat_percent between 1 and 80),
  waist_cm numeric(5,2) check (waist_cm between 20 and 300),
  notes text not null default '',
  created_at timestamptz not null default now(),
  constraint body_measurements_has_value check (
    weight_kg is not null
    or body_fat_percent is not null
    or waist_cm is not null
  )
);

create unique index body_measurements_user_date_key
  on public.body_measurements (user_id, measured_on);

create table public.nutrition_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  logged_on date not null default current_date,
  calories integer check (calories between 0 and 20000),
  protein_g numeric(6,2) check (protein_g between 0 and 2000),
  carbs_g numeric(6,2) check (carbs_g between 0 and 3000),
  fat_g numeric(6,2) check (fat_g between 0 and 1000),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index nutrition_logs_user_date_key
  on public.nutrition_logs (user_id, logged_on);

create table public.personal_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  exercise_name text not null,
  value numeric(10,2) not null check (value > 0),
  unit text not null check (unit in ('kg', 'lb', 'reps', 'seconds', 'meters', 'kilometers')),
  achieved_on date not null default current_date,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint personal_records_exercise_name_not_blank check (
    btrim(exercise_name) <> ''
  )
);

create index personal_records_user_exercise_idx
  on public.personal_records (user_id, exercise_name, achieved_on desc);

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

create trigger categories_set_updated_at
before update on public.categories
for each row execute function private.set_updated_at();

create trigger posts_set_updated_at
before update on public.posts
for each row execute function private.set_updated_at();

create trigger comments_set_updated_at
before update on public.comments
for each row execute function private.set_updated_at();

create trigger member_programs_set_updated_at
before update on public.member_programs
for each row execute function private.set_updated_at();

create trigger workout_logs_set_updated_at
before update on public.workout_logs
for each row execute function private.set_updated_at();

create trigger nutrition_logs_set_updated_at
before update on public.nutrition_logs
for each row execute function private.set_updated_at();

create trigger personal_records_set_updated_at
before update on public.personal_records
for each row execute function private.set_updated_at();

insert into public.statuses (status, label, is_public, sort_order)
values
  ('draft', 'Draft', false, 10),
  ('published', 'Published', true, 20),
  ('archived', 'Archived', false, 30)
on conflict (status) do nothing;

insert into public.categories (name, slug)
values
  ('Training', 'training'),
  ('Nutrition', 'nutrition'),
  ('Recovery', 'recovery'),
  ('Mindset', 'mindset')
on conflict do nothing;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.statuses enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.post_likes enable row level security;
alter table public.notifications enable row level security;
alter table public.member_programs enable row level security;
alter table public.workout_logs enable row level security;
alter table public.body_measurements enable row level security;
alter table public.nutrition_logs enable row level security;
alter table public.personal_records enable row level security;

create policy profiles_select_own_or_admin
on public.profiles for select
to authenticated
using (
  id = (select auth.uid())
  or (select private.current_user_is_admin())
);

create policy profiles_update_own
on public.profiles for update
to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy categories_select_active
on public.categories for select
to anon, authenticated
using (is_active);

create policy categories_select_content_admin
on public.categories for select
to authenticated
using ((select private.current_user_is_content_admin()));

create policy categories_insert_content_admin
on public.categories for insert
to authenticated
with check ((select private.current_user_is_content_admin()));

create policy categories_update_content_admin
on public.categories for update
to authenticated
using ((select private.current_user_is_content_admin()))
with check ((select private.current_user_is_content_admin()));

create policy categories_delete_content_admin
on public.categories for delete
to authenticated
using ((select private.current_user_is_content_admin()));

create policy statuses_select_all
on public.statuses for select
to anon, authenticated
using (true);

create policy posts_select_published
on public.posts for select
to anon, authenticated
using (
  exists (
    select 1
    from public.statuses
    where statuses.id = posts.status_id
      and statuses.is_public
  )
);

create policy posts_select_content_admin
on public.posts for select
to authenticated
using ((select private.current_user_is_content_admin()));

create policy posts_insert_content_admin
on public.posts for insert
to authenticated
with check ((select private.current_user_is_content_admin()));

create policy posts_update_content_admin
on public.posts for update
to authenticated
using ((select private.current_user_is_content_admin()))
with check ((select private.current_user_is_content_admin()));

create policy posts_delete_content_admin
on public.posts for delete
to authenticated
using ((select private.current_user_is_content_admin()));

create policy comments_select_visible
on public.comments for select
to anon, authenticated
using (not is_deleted);

create policy comments_select_own_or_admin
on public.comments for select
to authenticated
using (
  author_id = (select auth.uid())
  or (select private.current_user_is_admin())
);

create policy comments_insert_own
on public.comments for insert
to authenticated
with check (author_id = (select auth.uid()));

create policy comments_update_own_or_admin
on public.comments for update
to authenticated
using (
  author_id = (select auth.uid())
  or (select private.current_user_is_admin())
)
with check (
  author_id = (select auth.uid())
  or (select private.current_user_is_admin())
);

create policy comments_delete_own_or_admin
on public.comments for delete
to authenticated
using (
  author_id = (select auth.uid())
  or (select private.current_user_is_admin())
);

create policy post_likes_select_own_or_admin
on public.post_likes for select
to authenticated
using (
  user_id = (select auth.uid())
  or (select private.current_user_is_admin())
);

create policy post_likes_insert_own
on public.post_likes for insert
to authenticated
with check (user_id = (select auth.uid()));

create policy post_likes_delete_own
on public.post_likes for delete
to authenticated
using (user_id = (select auth.uid()));

create policy notifications_select_own_or_admin
on public.notifications for select
to authenticated
using (
  recipient_id = (select auth.uid())
  or (select private.current_user_is_admin())
);

create policy notifications_insert_admin
on public.notifications for insert
to authenticated
with check ((select private.current_user_is_admin()));

create policy notifications_update_own
on public.notifications for update
to authenticated
using (recipient_id = (select auth.uid()))
with check (recipient_id = (select auth.uid()));

create policy notifications_delete_admin
on public.notifications for delete
to authenticated
using ((select private.current_user_is_admin()));

create policy member_programs_select_own_or_admin
on public.member_programs for select
to authenticated
using (
  user_id = (select auth.uid())
  or (select private.current_user_is_admin())
);

create policy member_programs_insert_own
on public.member_programs for insert
to authenticated
with check (user_id = (select auth.uid()));

create policy member_programs_update_own
on public.member_programs for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create policy member_programs_delete_own
on public.member_programs for delete
to authenticated
using (user_id = (select auth.uid()));

create policy workout_logs_access_own_or_admin
on public.workout_logs for all
to authenticated
using (
  user_id = (select auth.uid())
  or (select private.current_user_is_admin())
)
with check (user_id = (select auth.uid()));

create policy body_measurements_access_own_or_admin
on public.body_measurements for all
to authenticated
using (
  user_id = (select auth.uid())
  or (select private.current_user_is_admin())
)
with check (user_id = (select auth.uid()));

create policy nutrition_logs_access_own_or_admin
on public.nutrition_logs for all
to authenticated
using (
  user_id = (select auth.uid())
  or (select private.current_user_is_admin())
)
with check (user_id = (select auth.uid()));

create policy personal_records_access_own_or_admin
on public.personal_records for all
to authenticated
using (
  user_id = (select auth.uid())
  or (select private.current_user_is_admin())
)
with check (user_id = (select auth.uid()));

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

grant usage on schema public to anon, authenticated;

grant select on public.categories, public.statuses, public.posts, public.comments
to anon;

grant select on public.profiles to authenticated;
grant update (full_name, username, bio, avatar_url, last_active_at)
on public.profiles to authenticated;

grant select, insert, update, delete
on public.categories, public.posts, public.comments
to authenticated;

grant select on public.statuses to authenticated;
grant select, insert, delete on public.post_likes to authenticated;
grant select, insert, delete on public.notifications to authenticated;
grant update (read_at) on public.notifications to authenticated;

grant select, insert, update, delete
on public.member_programs,
   public.workout_logs,
   public.body_measurements,
   public.nutrition_logs,
   public.personal_records
to authenticated;

grant usage, select on all sequences in schema public to authenticated;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'avatars',
    'avatars',
    true,
    5242880,
    array['image/jpeg', 'image/png', 'image/webp']
  ),
  (
    'post-images',
    'post-images',
    true,
    10485760,
    array['image/jpeg', 'image/png', 'image/webp']
  )
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy avatars_public_read
on storage.objects for select
to anon, authenticated
using (bucket_id = 'avatars');

create policy avatars_insert_own_folder
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy avatars_update_own_folder
on storage.objects for update
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy avatars_delete_own_folder
on storage.objects for delete
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy post_images_public_read
on storage.objects for select
to anon, authenticated
using (bucket_id = 'post-images');

create policy post_images_insert_content_admin
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'post-images'
  and (select private.current_user_is_content_admin())
);

create policy post_images_update_content_admin
on storage.objects for update
to authenticated
using (
  bucket_id = 'post-images'
  and (select private.current_user_is_content_admin())
)
with check (
  bucket_id = 'post-images'
  and (select private.current_user_is_content_admin())
);

create policy post_images_delete_content_admin
on storage.objects for delete
to authenticated
using (
  bucket_id = 'post-images'
  and (select private.current_user_is_content_admin())
);
